sonar.projectKey=shiweiumichedu_turtlecharter.com
sonar.organization=shiweiumichedu
sonar.sources=.
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/node_modules/**,**/dist/**,**/.git/**,**/venv/**
sonar.qualitygate.wait=true